### ISSUE TITLE
What is the input fasta file format?

### ISSUE THREAD

**Issue by wook2014** [MrTomRod/orthofinder-tools#1]
I used orthofinder-tools but my fasta file sequence name only have one field like '>gene-001', so the error occured
```
Failed to extract description for strain=G1
```
 I changed the fasta dir file sequence name and orthogroups.tsv, but it showed 
```
  File "/mnt/f/ortho/orthogroup_to_genename.py", line 106, in <listcomp>
    lambda ids: [gene_id_to_name[id] for id in ids])
KeyError: ''
```

**Comment by MrTomRod** [comment]
Your FASTAs don't seem to have any description.

Example:

```text
>gnl|extdb|STRAIN-XY_000001 DNA-directed RNA polymerase subunit beta' [Pediococcus stilesii]
MIDVNKFESMQIGLASPDKIRMWSYGEVKKPETINYRTLKPEKDGLFDERIFGPTKDYECACGKYKRIRY
...
```

From this protein, `DNA-directed RNA polymerase subunit beta` would be extracted.
