### ISSUE TITLE
Failed to extract description for strain=CerAGI:

### ISSUE THREAD

**Issue by shivank-parashar** [MrTomRod/orthofinder-tools#2]
I ran your specified command with all the required parameters but recieved an error when executed.
I've listed the command and the error which I got while running it.

```bash
$ annotate_orthogroups --orthogroups_tsv /home/shivank/Results_Aug23/Phylogenetic_Hierarchical_Orthogroups/N0.tsv --hog True --fasta_dir /home/shivank/protein/ --file_endings faa --out /home/shivank/outfile.tsv --simple True
AssertionError: Failed to extract description for strain=CerAGI:
gene.id=jgi|CerAGI|462322|estExt_Genewise1.C_1_t10001
gene.description=jgi|CerAGI|462322|estExt_Genewise1.C_1_t10001
description=['jgi|CerAGI|462322|estExt_Genewise1.C_1_t10001']
```

**Comment by MrTomRod** [comment]
Can you send me the files?

**Comment by shivank-parashar** [comment]
[CerAGI.fasta.zip](https://github.com/MrTomRod/orthofinder-tools/files/12442867/CerAGI.fasta.zip)
This is the file on which error was thrown. Rest other species files are having the same header accessions type for their respective fasta sequences.

**Comment by MrTomRod** [comment]
Will have a look in a few days when I'm back from holidays!

**Comment by MrTomRod** [comment]
Your FASTA files don't contain any descriptions, as described under [Prerequisites](https://github.com/MrTomRod/orthofinder-tools#prerequisites).

This does not work:
```text
>jgi|CerAGI|462322|estExt_Genewise1.C_1_t10001
MFLPKSGTTVDPGSTPEATKDADSFEEIGAELAQDAKIWGSYVQQTDRADREMIEGWHSSMDVLLIFAAL
...
```

Something like this is required:

```text
>jgi|CerAGI|462322|estExt_Genewise1.C_1_t10001 DNA-directed RNA polymerase subunit beta' [Pediococcus stilesii]
MFLPKSGTTVDPGSTPEATKDADSFEEIGAELAQDAKIWGSYVQQTDRADREMIEGWHSSMDVLLIFAAL
...
```

These could perhaps be added to existing FASTAs with a took like [bakta](https://github.com/oschwengers/bakta#user-provided-protein-sequences) or [prokka](https://github.com/tseemann/prokka#option---proteins), though I've never tried this. I usually use [PGAP](https://github.com/ncbi/pgap/wiki/) output FASTAs, but they can only be generated from _de novo_ annotations.
